apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
        - name: fastapi-container
          image: public.ecr.aws/e2v8h6j1/githubaction:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
