name: Delete Kops Cluster

on:
  workflow_dispatch:  # Run manually from GitHub Actions

jobs:
  delete-cluster:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-south-1
      KOPS_STATE_BUCKET: kopsbkt100
      CLUSTER_NAME: kopscluster.k8s.local

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Kops
        run: |
          curl -LO https://github.com/kubernetes/kops/releases/latest/download/kops-linux-amd64
          chmod +x kops-linux-amd64
          sudo mv kops-linux-amd64 /usr/local/bin/kops
          kops version

      - name: Set KOPS_STATE_STORE
        run: echo "KOPS_STATE_STORE=s3://${{ env.KOPS_STATE_BUCKET }}" >> $GITHUB_ENV

      - name: Delete Kops Cluster
        run: |
          export KOPS_STATE_STORE=s3://${{ env.KOPS_STATE_BUCKET }}
          
          if kops get cluster ${{ env.CLUSTER_NAME }} --state=${KOPS_STATE_STORE} > /dev/null 2>&1; then
            echo "Cluster found, deleting..."
            kops delete cluster --name=${{ env.CLUSTER_NAME }} --state=${KOPS_STATE_STORE} --yes
          else
            echo "Cluster not found, skipping deletion."
          fi

      - name: Delete Kops State S3 Bucket (Optional)
        run: |
          aws s3 rb s3://${{ env.KOPS_STATE_BUCKET }} --force || echo "S3 bucket already deleted"
